name: 保活

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 20 0 1 * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Update system and install zsh
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get install zsh -y
          
    - name: 提交保活
      run: |
       zsh random_cron.sh
       git_pwd='${{ secrets.GIT_PWD }}'
       git config --global user.name "magician8520"
       git config --global user.email "magician8520@outlook.com"
       git add .
       git commit -m '提交保活'
       git remote set-url origin http://magician8520:${git_pwd}@github.com/magician8520/mistep-wo.git
       git push
